/** 错误码表（规范 S09）。系统段 + 业务段（auth/perm/approval/ai；lead/quote 段随 P3+ 扩展） */
export enum ErrorCode {
  // 系统段
  INTERNAL = 'INTERNAL',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
  // auth 段（P1-01 认证）
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  // perm 段（P1-02 RBAC）
  PERM_DENIED = 'PERM_DENIED',
  // approval 段（P1-05 审批）
  APPROVAL_INVALID_STATE = 'APPROVAL_INVALID_STATE',
  // ai 段（P2 ai-dispatch 通道）
  AI_DISABLED = 'AI_DISABLED',
  AI_BUDGET_EXCEEDED = 'AI_BUDGET_EXCEEDED',
  AI_TASK_INVALID_STATE = 'AI_TASK_INVALID_STATE',
  AI_SIGNATURE_INVALID = 'AI_SIGNATURE_INVALID',
  // lead 段（P3 客资）
  LEAD_INVALID_STATE = 'LEAD_INVALID_STATE',
  LEAD_PARSE_FAILED = 'LEAD_PARSE_FAILED',
  LEAD_DUP_BATCH = 'LEAD_DUP_BATCH',
  LEAD_NOT_OWNER = 'LEAD_NOT_OWNER',
  // knowledge 段（P4 知识库）
  KNOWLEDGE_INVALID_STATE = 'KNOWLEDGE_INVALID_STATE',
  KNOWLEDGE_DUPLICATE_ACTIVE = 'KNOWLEDGE_DUPLICATE_ACTIVE',
  // delivery 段（P5 预约与施工）
  APPOINTMENT_CONFLICT = 'APPOINTMENT_CONFLICT',
  APPOINTMENT_INVALID_STATE = 'APPOINTMENT_INVALID_STATE',
  WORK_ORDER_INVALID_STATE = 'WORK_ORDER_INVALID_STATE',
  AFTERCARE_INVALID_STATE = 'AFTERCARE_INVALID_STATE',
  ORDER_INVALID_STATE = 'ORDER_INVALID_STATE',
  TECHNICIAN_SKILL_MISMATCH = 'TECHNICIAN_SKILL_MISMATCH',
}

export const ERROR_STATUS: Record<ErrorCode, number> = {
  [ErrorCode.INTERNAL]: 500,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.VALIDATION_FAILED]: 422,
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.CONFLICT]: 409,
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
  [ErrorCode.AUTH_ACCOUNT_DISABLED]: 403,
  [ErrorCode.AUTH_ACCOUNT_LOCKED]: 403,
  [ErrorCode.AUTH_TOKEN_INVALID]: 401,
  [ErrorCode.AUTH_TOKEN_EXPIRED]: 401,
  [ErrorCode.PERM_DENIED]: 403,
  [ErrorCode.APPROVAL_INVALID_STATE]: 409,
  [ErrorCode.AI_DISABLED]: 503,
  [ErrorCode.AI_BUDGET_EXCEEDED]: 429,
  [ErrorCode.AI_TASK_INVALID_STATE]: 409,
  [ErrorCode.AI_SIGNATURE_INVALID]: 401,
  [ErrorCode.LEAD_INVALID_STATE]: 409,
  [ErrorCode.LEAD_PARSE_FAILED]: 422,
  [ErrorCode.LEAD_DUP_BATCH]: 409,
  [ErrorCode.LEAD_NOT_OWNER]: 403,
  [ErrorCode.KNOWLEDGE_INVALID_STATE]: 409,
  [ErrorCode.KNOWLEDGE_DUPLICATE_ACTIVE]: 409,
  [ErrorCode.APPOINTMENT_CONFLICT]: 409,
  [ErrorCode.APPOINTMENT_INVALID_STATE]: 409,
  [ErrorCode.WORK_ORDER_INVALID_STATE]: 409,
  [ErrorCode.AFTERCARE_INVALID_STATE]: 409,
  [ErrorCode.ORDER_INVALID_STATE]: 409,
  [ErrorCode.TECHNICIAN_SKILL_MISMATCH]: 422,
};
